import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";

const TH_BASE = process.env.THCODE_BASE || "https://tokenharbor.ai";
const POLL_INTERVAL_MS = 2000;
const POLL_TIMEOUT_MS = 5 * 60 * 1000;

const BANNER = `
  ┌─────────────────────────────────────────────────┐
  │  thcode — Token Harbor coding agent             │
  │  Powered by codewhale + TH gateway              │
  └─────────────────────────────────────────────────┘
`;

function tryOpenInBrowser(url) {
  const cmd =
    process.platform === "darwin" ? "open"
    : process.platform === "win32" ? "start"
    : "xdg-open";
  try {
    spawn(cmd, [url], { stdio: "ignore", detached: true }).unref();
    return true;
  } catch {
    return false;
  }
}

async function initSession() {
  const r = await fetch(`${TH_BASE}/api/cli/auth/init`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ client_label: "thcode" }),
  });
  if (!r.ok) throw new Error(`init failed: HTTP ${r.status}`);
  return r.json();
}

async function poll(pollUrl) {
  const deadline = Date.now() + POLL_TIMEOUT_MS;
  let lastStatus = "";
  while (Date.now() < deadline) {
    let body;
    try {
      const r = await fetch(pollUrl);
      body = await r.json();
    } catch {
      await new Promise((s) => setTimeout(s, POLL_INTERVAL_MS));
      continue;
    }
    if (body.status === "approved" && body.key) return body.key;
    if (body.status === "expired" || body.status === "denied" || body.status === "not_found") {
      throw new Error(`Login ${body.status}.`);
    }
    if (body.status !== lastStatus) lastStatus = body.status;
    await new Promise((s) => setTimeout(s, POLL_INTERVAL_MS));
  }
  throw new Error("Login timed out after 5 minutes. Run thcode again.");
}

const CODEWHALE_CONFIG_DIR = path.join(homedir(), ".deepseek");
const CODEWHALE_CONFIG_FILE = path.join(CODEWHALE_CONFIG_DIR, "config.toml");

function writeCodewhaleConfig(apiKey) {
  mkdirSync(CODEWHALE_CONFIG_DIR, { recursive: true });
  // codewhale honors api_key / base_url / model / provider keys in
  // ~/.deepseek/config.toml; openai-compatible provider lets it talk
  // to any OpenAI-style endpoint, which is exactly what TH exposes.
  // codewhale's `provider` is a fixed enum; OpenAI-compatible
  // endpoints go under `provider = "openai"` with base_url override.
  // The TH gateway speaks OpenAI shape exactly, so this is correct.
  const toml =
`# Token Harbor — auto-generated by thcode wrapper. Edit ~/.deepseek/config.toml
# manually only if you want to bypass admin-managed defaults.

provider = "openai"
base_url = "${TH_BASE}/v1"
api_key  = "${apiKey}"
model    = "tokenharbor-smart-thinking"

[agent]
max_concurrent_subagents = 10
`;
  writeFileSync(CODEWHALE_CONFIG_FILE, toml, { mode: 0o600 });
  try { chmodSync(CODEWHALE_CONFIG_FILE, 0o600); } catch {}
}

export async function runOnboarding() {
  if (existsSync(CODEWHALE_CONFIG_FILE)) {
    const cfg = readFileSync(CODEWHALE_CONFIG_FILE, "utf8");
    if (cfg.includes(TH_BASE) && /api_key\s*=\s*"thk_live_/.test(cfg)) {
      // Already set up — skip onboard.
      return;
    }
  }

  process.stdout.write(BANNER);
  console.log("First-run setup. Starting browser login…\n");

  const { session_id, auth_url, poll_url } = await initSession();

  console.log("Open this URL to sign in (the browser should open automatically):");
  console.log(`\n  ${auth_url}\n`);
  tryOpenInBrowser(auth_url);
  console.log(`Waiting for approval (session ${session_id.slice(0, 8)}…)`);

  const key = await poll(poll_url);
  writeCodewhaleConfig(key);

  console.log("\nLogged in.");
  console.log("  Config saved to  " + CODEWHALE_CONFIG_FILE);
  console.log("\nLaunching codewhale…\n");
}

export function hasTHProvider() {
  if (!existsSync(CODEWHALE_CONFIG_FILE)) return false;
  try {
    const cfg = readFileSync(CODEWHALE_CONFIG_FILE, "utf8");
    return cfg.includes(TH_BASE) && /api_key\s*=\s*"thk_live_/.test(cfg);
  } catch {
    return false;
  }
}
